# Site settings
title: Computer says 'no'
header-img: img/home-bg.png
email: sebgertz@gmail.com
copyright_name: scirocco21
description: > # this means to ignore newlines until "baseurl:"
  ..until it finally says 'yes'! I blog about this here. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  scirocco21
learn_profile: scirocco21
email_username: sebgertz@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
